"""
PIMS PRO
PDF Report Generator

Developer:
M. Fahad Zafar
"""
import pandas as pd
import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from src.charts import export_pdf_charts
from src.risk import risk_matrix_chart

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    PageBreak
)
def add_footer(canvas, doc):

    canvas.saveState()

    canvas.setFont("Helvetica", 9)

    width, height = A4

    footer_text = (
        "Generated by PIMS PRO | Version 1.0 | "
        "Mechanical Engineering Project"
    )

    # Calculate text width
    text_width = canvas.stringWidth(
        footer_text,
        "Helvetica",
        9
    )

    # Center position
    x_position = (width - text_width) / 2

    canvas.drawString(
        x_position,
        20,
        footer_text
    )

    canvas.restoreState()

def generate_pdf_report(data):

    history = pd.read_csv("data/inspection_history.csv")

    # Filter only the current pipeline
    history = history[
        history["Pipe ID"] == data["pipe_id"]
    ]

    # Generate dynamic risk matrix
    fig = risk_matrix_chart(
        data["likelihood"],
        data["consequence"]
    )

    fig.write_image(
        "assets/charts/risk_matrix.png",
        width=900,
        height=900
    )
    # Generate charts only for this pipeline
    export_pdf_charts(history)
    
    risk_matrix_chart(
        data["likelihood"],
        data["consequence"]
    )
    # -----------------------------
    # Create Reports Folder
    # -----------------------------
    os.makedirs("reports/inspection_reports", exist_ok=True)

    # -----------------------------
    # Automatic File Naming
    # -----------------------------

    pipe_id = data["pipe_id"]

    report_date = datetime.now().strftime("%Y-%m-%d")

    filename = os.path.join(
        "reports",
        "inspection_reports",
        f"{pipe_id}_Inspection_Report_{report_date}.pdf"
    )

    # -----------------------------
    # PDF Document
    # -----------------------------
    doc = SimpleDocTemplate(
        filename,
        pagesize=A4
    )

    story = []

    styles = getSampleStyleSheet()

    # -----------------------------
    # Styles
    # -----------------------------
    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.spaceAfter = 10

    subtitle_style = styles["Heading2"]
    subtitle_style.alignment = TA_CENTER

    normal_center = styles["BodyText"]
    normal_center.alignment = TA_CENTER

    # -----------------------------
    # Section Heading Style
    # -----------------------------
    section_style = styles["Heading2"]
    section_style.textColor = colors.HexColor("#0F4C81")
    section_style.spaceAfter = 8
    # -----------------------------
    # Logo
    # -----------------------------
    logo_path = os.path.join(
        "assets",
        "logo",
        "pims_logo.png"
    )

    if os.path.exists(logo_path):

        logo = Image(logo_path)

        logo.drawWidth = 1.2 * inch
        logo.drawHeight = 1.2 * inch
        logo.hAlign = "CENTER"

        story.append(logo)
        story.append(Spacer(1, 0.20 * inch))

    # -----------------------------
    # Header
    # -----------------------------
    story.append(
        Paragraph(
            "PIMS PRO",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Pipeline Integrity Management System",
            subtitle_style
        )
    )

    story.append(
        Paragraph(
            "Pipeline Corrosion Assessment & Remaining Life Calculator",
            normal_center
        )
    )

    story.append(Spacer(1, 0.30 * inch))

    # -----------------------------
    # Report Information
    # -----------------------------
    report_data = [

        ["Version", "1.0"],

        ["Developer", "M. Fahad Zafar"],

        ["Report File", os.path.basename(filename)],

        ["Generation Date", datetime.now().strftime("%d %B %Y")]

    ]

    report_table = Table(
        report_data,
        colWidths=[170, 250]
    )

    report_table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    story.append(report_table)

    story.append(Spacer(1, 0.35 * inch))

    # -----------------------------
    # Inspection Information
    # -----------------------------
    story.append(
        Paragraph(
            "Inspection Information",
            section_style
        )
    )

    story.append(Spacer(1, 0.15 * inch))

    inspection_data = [

        ["Pipe ID", data["pipe_id"]],

        ["Pipeline Name", data["pipeline_name"]],

        ["Material", data["material"]],

        ["Fluid", data["fluid"]],

        ["Inspector", data["inspector"]],

        ["Inspection Date", data["inspection_date"]],

        ["Operating Pressure", f'{data["pressure"]} MPa']

    ]

    inspection_table = Table(
        inspection_data,
        colWidths=[170, 250]
    )

    inspection_table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    story.append(inspection_table)
    story.append(Spacer(1, 0.35 * inch))

    story.append(
        Paragraph(
            "Engineering Calculations",
            section_style
        )
    )

    story.append(Spacer(1, 0.15 * inch))

    calculation_data = [

        ["Parameter", "Value"],

        ["Corrosion Rate",
        f"{data['corrosion_rate']:.2f} mm/year"],

        ["Minimum Thickness",
        f"{data['minimum_thickness']:.2f} mm"],

        ["Remaining Life",
        f"{data['remaining_life']:.2f} years"],

        ["Safety Factor",
        f"{data['safety_factor']:.2f}"],

        ["Corrosion Loss",
        f"{data['corrosion_loss']:.2f} %"],

        ["Health Score",
        f"{data['health_score']:.2f} %"],

        ["Failure Year",
        str(data["failure_year"])]
    ]

    calculation_table = Table(
        calculation_data,
        colWidths=[220, 180]
    )

    calculation_table.setStyle(
        TableStyle([

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),

            ("BACKGROUND", (0, 1), (0, -1), colors.lightgrey),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ("TOPPADDING", (0, 0), (-1, -1), 8),

            ("VALIGN", (0, 0), (-1, -1), "MIDDLE")

        ])
    )

    story.append(calculation_table)
    story.append(Spacer(1, 0.35 * inch))

    story.append(
        Paragraph(
            "KPI Summary",
            section_style
        )
    )

    story.append(Spacer(1, 0.20 * inch))

    kpi_data = [
        ["Health Score", f"{data['health_score']:.2f}%"],
        ["Risk Level", data["risk_level"]],
        ["Remaining Life", f"{data['remaining_life']:.2f} Years"],
        ["Corrosion Rate", f"{data['corrosion_rate']:.2f} mm/year"]
    ]

    kpi_table = Table(
        kpi_data,
        colWidths=[220,180]
    )

    kpi_table.setStyle(
        TableStyle([
            ("GRID",(0,0),(-1,-1),1,colors.black),
            ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#0F4C81")),

            ("TEXTCOLOR",(0,0),(0,-1),colors.white),

            ("FONTNAME",(0,0),(-1,-1),"Helvetica-Bold"),

            ("BACKGROUND",(1,0),(1,0),colors.lightgreen),

            ("BACKGROUND",(1,1),(1,1),colors.yellow),

            ("BACKGROUND",(1,2),(1,2),colors.beige),

            ("BACKGROUND",(1,3),(1,3),colors.lightblue),

            ("ALIGN",(0,0),(-1,-1),"CENTER"),

            ("VALIGN",(0,0),(-1,-1),"MIDDLE"),

            ("BOTTOMPADDING",(0,0),(-1,-1),10),

            ("TOPPADDING",(0,0),(-1,-1),10),

        ])
    )
    story.append(kpi_table)
    story.append(Spacer(1, 0.30 * inch))

    story.append(PageBreak())

    story.append(
        Paragraph(
            "Corrosion Trend",
            section_style
        )
    )

    story.append(Spacer(1, 0.20 * inch))

    chart = os.path.join(
        "assets",
        "charts",
        "corrosion_trend.png"
    )

    if os.path.exists(chart):

        img = Image(chart)

        img.drawWidth = 6.5 * inch
        img.drawHeight = 3.8 * inch
        img.hAlign = "CENTER"

        story.append(img)

    story.append(Spacer(1, 0.30 * inch))


    story.append(PageBreak())

    story.append(
        Paragraph(
            "Thickness History",
            section_style
        )
    )

    story.append(Spacer(1, 0.20 * inch))

    chart = os.path.join(
        "assets",
        "charts",
        "thickness_history.png"
    )

    if os.path.exists(chart):

        img = Image(chart)

        img.drawWidth = 6.5 * inch
        img.drawHeight = 3.8 * inch
        img.hAlign = "CENTER"

        story.append(img)

    story.append(Spacer(1, 0.30 * inch))

    story.append(PageBreak())

    story.append(
        Paragraph(
            "Remaining Life Trend",
            section_style
        )
    )

    story.append(Spacer(1, 0.20 * inch))

    chart = os.path.join(
        "assets",
        "charts",
        "remaining_life.png"
    )

    if os.path.exists(chart):

        img = Image(chart)

        img.drawWidth = 6.5 * inch
        img.drawHeight = 3.8 * inch
        img.hAlign = "CENTER"

        story.append(img)

    story.append(Spacer(1, 0.30 * inch))


    story.append(PageBreak())

    story.append(
        Paragraph(
            "Health Trend",
            section_style
        )
    )

    story.append(Spacer(1, 0.20 * inch))

    chart = os.path.join(
        "assets",
        "charts",
        "health_trend.png"
    )

    if os.path.exists(chart):

        img = Image(chart)

        img.drawWidth = 6.5 * inch
        img.drawHeight = 3.8 * inch
        img.hAlign = "CENTER"

        story.append(img)

    story.append(Spacer(1, 0.30 * inch))


    story.append(PageBreak())

    story.append(
        Paragraph(
            "Engineering KPI Gauges",
            section_style
        )
    )

    story.append(Spacer(1, 0.20 * inch))
    

    health = os.path.join(
        "assets", "charts", "health_gauge.png"
    )

    corrosion = os.path.join(
        "assets", "charts", "corrosion_rate_gauge.png"
    )

    life = os.path.join(
        "assets", "charts", "remaining_life_gauge.png"
    )

    risk = os.path.join(
        "assets", "charts", "risk_score_gauge.png"
    )

    health_img = Image(health, width=2.6*inch, height=2.6*inch)
    corrosion_img = Image(corrosion, width=2.6*inch, height=2.6*inch)
    life_img = Image(life, width=2.6*inch, height=2.6*inch)
    risk_img = Image(risk, width=2.6*inch, height=2.6*inch)

    gauge_table = Table(
        [
            [health_img, corrosion_img],
            [life_img, risk_img]
        ],
        colWidths=[3 * inch, 3 * inch]
    )

    gauge_table.setStyle(
        TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 10)
        ])
    )
    story.append(gauge_table)
    story.append(Spacer(1, 0.30 * inch))
    
    story.append(Spacer(1, 0.30 * inch))

    # -----------------------------
    # Risk Assessment
    # -----------------------------
    story.append(PageBreak())

    story.append(
        Paragraph(
            "Risk Assessment",
            section_style
        )
    )

    story.append(Spacer(1, 0.15 * inch))

    risk_data = [

        ["Parameter", "Value"],

        ["Likelihood", data["likelihood"]],

        ["Consequence", data["consequence"]],

        ["Risk Score", data["risk_score"]],

        ["Risk Category", data["risk_level"]]

    ]

    risk_table = Table(
        risk_data,
        colWidths=[220, 180]
    )

    risk_table.setStyle(
        TableStyle([

            ("GRID", (0,0), (-1,-1), 1, colors.black),

            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#8B0000")),

            ("TEXTCOLOR", (0,0), (-1,0), colors.white),

            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

            ("BACKGROUND", (0,1), (0,-1), colors.lightgrey),

            ("ALIGN", (0,0), (-1,-1), "CENTER"),

            ("BOTTOMPADDING", (0,0), (-1,-1), 8),

            ("TOPPADDING", (0,0), (-1,-1), 8)

        ])
    )

    story.append(risk_table)

    story.append(Spacer(1, 0.30 * inch))

    # -----------------------------
    # Risk Matrix
    # -----------------------------
    story.append(PageBreak())

    story.append(
        Paragraph(
            "5 × 5 Risk Matrix",
            section_style
        )
    )

    story.append(Spacer(1, 0.20 * inch))

    matrix = os.path.join(
        "assets",
        "charts",
        "risk_matrix.png"
    )

    if os.path.exists(matrix):

        img = Image(matrix)

        img.drawWidth = 6.5 * inch
        img.drawHeight = 6 * inch
        img.hAlign = "CENTER"

        story.append(img)


    # -----------------------------
    # Engineering Recommendation
    # -----------------------------
    story.append(PageBreak())

    story.append(
        Paragraph(
            "Engineering Recommendation",
            section_style
        )
    )

    story.append(Spacer(1,0.20*inch))
    
    health = data["health_score"]
    remaining = data["remaining_life"]
    risk = data["risk_level"]

    if health >= 80 and remaining >= 15:

        decision = "Pipeline Suitable for Continued Service"

        suggestion = "Routine inspection only."

        interval = "Next inspection after 5 years."

        priority = "LOW"

        warning = "No immediate engineering concern."

    elif health >= 60:

        decision = "Pipeline Acceptable with Monitoring"

        suggestion = "Increase inspection frequency."

        interval = "Next inspection after 2 years."

        priority = "MEDIUM"

        warning = "Moderate corrosion detected."

    elif health >= 40:

        decision = "Pipeline Requires Maintenance"

        suggestion = "Repair or replace damaged section."

        interval = "Inspect within 6 months."

        priority = "HIGH"

        warning = "Pipeline approaching minimum thickness."

    else:

        decision = "Pipeline Unsafe for Service"

        suggestion = "Immediate shutdown and replacement."

        interval = "Immediate inspection required."

        priority = "URGENT"

        warning = "Critical structural integrity risk."
        
    recommendation_data = [

        ["Overall Decision", decision],

        ["Maintenance Suggestion", suggestion],

        ["Inspection Interval", interval],

        ["Priority", priority],

        ["Warning Message", warning]

    ]    
    
    recommendation_table = Table(

        recommendation_data,

        colWidths=[220,250]

    )
    
    recommendation_table.setStyle(

        TableStyle([

            ("GRID",(0,0),(-1,-1),1,colors.black),

            ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#0F4C81")),

            ("TEXTCOLOR",(0,0),(0,-1),colors.white),

            ("FONTNAME",(0,0),(-1,-1),"Helvetica-Bold"),

            ("ALIGN",(0,0),(-1,-1),"CENTER"),

            ("VALIGN",(0,0),(-1,-1),"MIDDLE"),

            ("BOTTOMPADDING",(0,0),(-1,-1),10),

            ("TOPPADDING",(0,0),(-1,-1),10)

        ])

    )
    
    story.append(recommendation_table)

    story.append(Spacer(1,0.30*inch))
    
    
    
    # -----------------------------
    # Inspection Summary
    # -----------------------------
    story.append(
        Paragraph(
            "Inspection Summary",
            section_style
        )
    )

    story.append(Spacer(1,0.20*inch))
    
    summary = (
        f"The pipeline ({data['pipe_id']}) remains suitable for continued operation. "
        f"The measured corrosion rate is {data['corrosion_rate']:.2f} mm/year "
        f"with an estimated remaining service life of "
        f"{data['remaining_life']:.2f} years. "
        f"The calculated health score is {data['health_score']:.1f}% "
        f"and the overall risk category is {data['risk_level']}. "
        f"{suggestion}"
    )
    
    story.append(
        Paragraph(
            summary,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,0.25*inch))
    
    story.append(
        Paragraph(
            "<b>Conclusion:</b>",
            styles["Heading3"]
        )
    )
    
    
    conclusion = (
        "Based on the inspection data and engineering calculations "
        "performed in accordance with ASME B31.3 and API 570 principles, "
        "the pipeline integrity has been evaluated and appropriate "
        "maintenance recommendations have been provided to support "
        "safe and reliable operation."
    )
    
    story.append(
        Paragraph(
            conclusion,
            styles["BodyText"]
        )
    )
    
    story.append(Spacer(1,0.30*inch))
    
    
    # -----------------------------
    # Engineering Notes
    # -----------------------------
    story.append(
        Paragraph(
            "Engineering Notes",
            section_style
        )
    )

    story.append(Spacer(1,0.20*inch))
    story.append(
        Paragraph(
            "Engineer observations, maintenance remarks, or site comments may be recorded below.",
            styles["Italic"]
        )
    )

    story.append(Spacer(1,0.20*inch))
    
    story.append(
        Paragraph(
            "_______________________________________________",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,0.15*inch))

    story.append(
        Paragraph(
            "_______________________________________________",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,0.15*inch))

    story.append(
        Paragraph(
            "_______________________________________________",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,0.15*inch))
    
    # -----------------------------
    # Engineering Standards
    # -----------------------------
    story.append(Spacer(1,0.30*inch))

    story.append(
        Paragraph(
            "Engineering Standards",
            section_style
        )
    )

    story.append(Spacer(1,0.15*inch))
    
    standards = [

        "• ASME B31.3 – Process Piping",

        "• API 570 – Piping Inspection Code"

    ]
    
    for item in standards:

        story.append(
            Paragraph(
                item,
                styles["BodyText"]
            )
        )
        
    story.append(Spacer(1,0.20*inch))

    story.append(
        Paragraph(
            "The engineering calculations, integrity assessment, corrosion evaluation, remaining life estimation, and inspection recommendations presented in this report are based on the principles and methodologies defined in ASME B31.3 and API 570. The report is intended as an engineering decision-support document and should be reviewed by qualified personnel before maintenance or operational decisions are made.",
            styles["BodyText"]
        )
    )    
    # -----------------------------
    # Build PDF
    # -----------------------------
    doc.build(
        story,
        onFirstPage=add_footer,
        onLaterPages=add_footer
    )

    return filename